### PR TITLE
Button refactor

### PR DESCRIPTION
**Pull request by jrauh**
- BIG update to action example page
- Update to navigation example page
- Refactored `actions.scss`
- `button--icon--small` now uses `button--icon`
- Updated menu icon name to be more semantically correct

### CODE REVIEW

**Comment by aknobloch3** [comment]
Couple comments when working through this:

- Under *Icons* --> Transparent Buttons: The icon is getting `margin-left: -0.2rem;` Do we need this? Kind of throws off the hover on Transparent Buttons. But it does makes the Default and Border look good.
- Also, do we want to re-introduce the outline on buttons for accessibility?

**Comment by jrauh** [comment]
> Couple comments when working through this:
> 
> * Under _Icons_ --> Transparent Buttons: The icon is getting `margin-left: -0.2rem;` Do we need this? Kind of throws off the hover on Transparent Buttons. But it does makes the Default and Border look good.
> * Also, do we want to re-introduce the outline on buttons for accessibility?

1. I noticed the same thing on the hover for transparent buttons. The reason I didn't touch it is because when you left or right justify a transparent button, it doesn't optically align to the content due to the side padding. I'd be fine changing it though. 
2. I wondered this too. Could that update wait and just merit a new version once Paragon is live? It just seems like it's more work than we have time for right now to get this out of beta. Thoughts?

**Comment by aknobloch3** [comment]
> > Couple comments when working through this:
> > 
> > * Under _Icons_ --> Transparent Buttons: The icon is getting `margin-left: -0.2rem;` Do we need this? Kind of throws off the hover on Transparent Buttons. But it does makes the Default and Border look good.
> > * Also, do we want to re-introduce the outline on buttons for accessibility?
> 
> 1. I noticed the same thing on the hover for transparent buttons. The reason I didn't touch it is because when you left or right justify a transparent button, it doesn't optically align to the content due to the side padding. I'd be fine changing it though.
> 2. I wondered this too. Could that update wait and just merit a new version once Paragon is live? It just seems like it's more work than we have time for right now to get this out of beta. Thoughts?
1. Yeah, it is just a small thing... so I don't have a huge opinion on it. Ok with leaving it for now.
2. Seems like a big enough change to update once Paragon is live. I could get on board with that.

**Comment by aknobloch3** [comment]
Oooo one other thing. The example code is all `className`. Are we planning on moving towards this? My last thought on this was that we are still sticking with `class` for code examples.

**Comment by jrauh** [comment]
> Oooo one other thing. The example code is all `className`. Are we planning on moving towards this? My last thought on this was that we are still sticking with `class` for code examples.

Oh yeah. Good catch. I think a few weeks ago we said we'd use `class` instead of `className`

**Comment by jrauh** [comment]
`button-group` was bloated and inconsistent with other default button styling. I simplified it so we now can call colors and styles with the standard `button--blue` or `button--border` instead of `button-group--blue` or `button-group--border`.

**Pull request merged**
