### PR TITLE
Add icon sizing utility classes

### PR DESCRIPTION
**Pull request by aknobloch3**
Addresses #89 
- Add icon content and color values to scss maps (clean up the code a bit)
- Add examples for icon class utilities
- Change icon sizing to be relative to parent container

Screen Shot 2020-12-15 at 11 33 46 AM
Screen Shot 2020-12-15 at 11 33 54 AM

### CODE REVIEW

**Review by coryclubb — APPROVED** [review]
Nice work! Now I probably need to create a story to clean up signup icons.

**Comment by jrauh** [comment]
At some point, we should change the name of our icon library to remove "dashing" terminology.

**Review by jrauh — COMMENTED** [review]
I can’t get Paragon running right now (it’s been well over a year so I’m not too surprised). 

I'm curious how the icon size change plays with other components that reference them, such as card-banners or button-icons. Were you able to test those after this change?

**Comment by aknobloch3** [comment]
> I can’t get Paragon running right now (it’s been well over a year so I’m not too surprised).
> 
> I'm curious how the icon size change plays with other components that reference them, such as card-banners or button-icons. Were you able to test those after this change?

Banners are unaffected by this change because usually our icon and text are siblings. So the relative sizing does not change the size here. Icons stay at the base font size (16px).

Icons in buttons were affected, but in a good way. The icon now becomes the same size as the text, which helps align it better.

That only other change is the "tooltip" we have next to from labels. Since the label text is smaller than 16px, the tooltip shrunk to the size of the label text (12.8px).

**Comment by jrauh** [comment]
> That only other change is the "tooltip" we have next to from labels. Since the label text is smaller than 16px, the tooltip shrunk to the size of the label text (12.8px)

Awesome, thanks! One thought for tooltips (and clippies) could be override that and increase the size, since it's a selectable item. 12px seems too small of a touch-target.

**Review by Nevren — APPROVED** [review]
Nice work!

**Review by jrauh — APPROVED** [review]
I like it.

**Pull request merged**
